### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by wvdongen**
- Bump to PHP 8
- Update dependencies to avoid conflicts in mondern projects
- Add DTD validation
- Fix Psalm checks

Perhaps you want to make this available under a new tag (3.0.0)

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
I'm not seeing where xmlstarlet is being used in the code?

**Comment by wvdongen** [comment]
It is used for the DTD validation: https://github.com/DavidGoodwin/nmap/pull/4/files#diff-b6fa647b645ca8fda12d85174924f3c25334441ff7bea24c9abe5491d68c3e74R74

**Comment by DavidGoodwin** [comment]
👓

**Comment by DavidGoodwin** [comment]
tagged with 3.0.0

**Pull request merged**
